### ISSUE TITLE
Mikrotik Jammer 

### ISSUE THREAD

**Issue by Racco18** [alexanderfefelov/mikrotik-routeros-scripts#1]
DO i need to change the firmware to work? I added the scrip and all wifes are seem in my warehouse

**Comment by alexanderfefelov** [comment]
Run `export compact` and copy the output here.

**Comment by Racco18** [comment]
Sorry, I'm not an expert my workers know a little. I put in a PTP mikrotik
pointing to a small island 3 feet antena.

This people never pay an we want to jamm the signal.

If you can help me to buy the right equipment in ebay or I can buy from you
parts or all.

**Comment by alexanderfefelov** [comment]
Is this legal in your country?

**Comment by Racco18** [comment]
I'm in houston but the island is close to Belize, there is no laws there

**Comment by alexanderfefelov** [comment]
PTP? What does this mean? Point-to-point?

**Comment by Racco18** [comment]
Yes

**Comment by Racco18** [comment]
Yes, from the main land Internet is send by ptp antenna. Then Internet is
send wired and wireless.

I want to Jamm the main feed from the mainland

**Comment by alexanderfefelov** [comment]
My script is able to jam access point only, not station. It is designed for home use.

**Comment by alexanderfefelov** [comment]
> I want to Jamm the main feed from the mainland

Just turn it off.

**Comment by Racco18** [comment]
I wish you could help

**Comment by Racco18** [comment]
I don't  have access to there land anymore. I want to do it from 1000 feet
away with a strong antenna and amp

**Comment by alexanderfefelov** [comment]
> I wish you could help

I need more data. Draw me some scheme.

**Comment by Racco18** [comment]
I can text you with whatapp

**Comment by Racco18** [comment]
There is a YouTube where the ptp was jamm with a custom firmware but I
don't Know how

**Comment by alexanderfefelov** [comment]
> I can text you with whatapp

Let's continue on GitHub. Maybe someone else will be interested in reading it.

**Comment by Racco18** [comment]
Can you delete my number? I didn't know it was public

**Comment by alexanderfefelov** [comment]
> but I don't Know how

I need a schematic of your network.

**Comment by alexanderfefelov** [comment]
> Can you delete my number?

Done.

**Comment by PH03N1X101** [comment]
@alexanderfefelov Hello does ur script run outdoor? 5GHZ Mikrotik SXT to jam another routerboard
